/**
 * This file was auto-generated by openapi-typescript.
 */

export interface Response {
  /** @description API response status (e.g. OK). */
  status: string
  /** @description Copyright message. */
  copyright: string
  /** @description Number of articles in the results (e.g. 20). */
  num_results: number
  /** @description Array of articles. */
  results: Definitions["Article"][]
}

export interface Definitions {
  Article: {
    /** @description Article's URL. */
    url: string
    /** @description Semicolon separated list of keywords. */
    adx_keywords: string
    /** @description Article's subsection (e.g. Politics). Can be empty string. */
    subsection: string
    /** @description Deprecated. Set to null. */
    column: string
    /** @description Deprecated. Set to 0. */
    eta_id: number
    /** @description Article's section (e.g. Sports). */
    section: string
    /** @description Asset ID number (e.g. 100000007772696). */
    id: number
    /** @description Asset ID number (e.g. 100000007772696). */
    asset_id: number
    /** @description Article's section (e.g. sports). */
    nytdsection: string
    /** @description Article's byline (e.g. By Thomas L. Friedman). */
    byline: string
    /** @description Asset type (e.g. Article, Interactive, ...). */
    type: string
    /** @description Article's headline (e.g. When the Cellos Play, the Cows Come Home). */
    title: string
    /** @description Brief summary of the article. */
    abstract: string
    /** @description When the article was published on the web (e.g. 2021-04-19). */
    published_date: string
    /** @description Publisher (e.g. New York Times). */
    source: string
    /** @description When the article was last updated (e.g. 2021-05-12 06:32:03). */
    updated: string
    /** @description Array of description facets (e.g. Quarantine (Life and Culture)). */
    des_facet: string[]
    /** @description Array of organization facets (e.g. Sullivan Street Bakery). */
    org_facet: string[]
    /** @description Array of person facets (e.g. Bittman, Mark). */
    per_facet: string[]
    /** @description Array of geographic facets (e.g. Canada). */
    geo_facet: string[]
    /** @description Array of images. */
    media: Definitions["Media"][]
    /** @description An article's globally unique identifier. */
    uri: string
  }
  Media: {
    /** @description Asset type (e.g. image). */
    type: string
    /** @description Asset subtype (e.g. photo). */
    subtype: string
    /** @description Media caption. */
    caption: string
    /** @description Media credit. */
    copyright: string
    /** @description Whether media is approved for syndication. */
    approved_for_syndication: boolean
    /** @description Media metadata (url, width, height, ...). */
    "media-metadata": Definitions["MediaMetadata"][]
  }
  MediaMetadata: {
    /** @description Image's URL. */
    url: string
    /** @description Image's crop name. */
    format: string
    /** @description Image's height (e.g. 293). */
    height: number
    /** @description Image's width (e.g. 440). */
    width: number
  }
}
